# Generated by Django 4.0 on 2021-12-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Added_date',
            new_name='added_date',
        ),
    ]
