# Generated by Django 3.2.9 on 2022-01-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220117_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
